-- SE DÉPLACER SUR LA DATABASE
USE `webDevelopment`;
-- CRÉE LA TABLE LANGUAGES
CREATE TABLE `languages` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `languages` VARCHAR(100),
    CONSTRAINT PK_id PRIMARY KEY(`id`)
    );
-- CRÉER LA TABLE TOOLS
CREATE TABLE `tools` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tool` VARCHAR(100),
    CONSTRAINT PK_id PRIMARY KEY(`id`)
    );
-- CRÉER LA TABLE FRAMEWORKS
CREATE TABLE `frameworks` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100),
    CONSTRAINT PK_id PRIMARY KEY(`id`)
    );
-- CRÉER LA TABLE LIBRARIES
CREATE TABLE `libraries` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `library` VARCHAR(100),
    CONSTRAINT PK_id PRIMARY KEY(`id`)
    );
-- CRÉER LA TABLE IDE
CREATE TABLE `ide` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ideName` VARCHAR(100),
    CONSTRAINT PK_id PRIMARY KEY(`id`)
    );
-- CRÉER LA TABLE FRAMEWORKS SI ELLE N'EXISTE PAS
CREATE TABLE IF NOT EXISTS `frameworks` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR (100),
    CONSTRAINT PK_id PRIMARY KEY(`id`)
);
-- SUPPRIMER LA TABLE TOOLS SI ELLE EXISTE
DROP TABLE IF EXISTS `tools`;
-- SUPPRIMER LA TABLE LIBRARIES
DROP TABLE `libraries`;
-- SUPPRIMER LA TABLE IDE
DROP TABLE `ide`;
